// INSTALED EXTENSIONS REST CLIENT
@host = localhost:4000

### URL ID
GET http://{{host}}/api/manga/read/1
content-type: application/json
###

### URL param 
GET  http://{{host}}/api/manga/read?order=start_d&score=9%2C8&score=4,5,6 
content-type: application/json
###

### URL regular
GET http://{{host}}/api/manga/read/order=title
content-type: application/json
###
