// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/manga.proto

package manga

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignment struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TitleEn              string               `protobuf:"bytes,3,opt,name=title_en,json=titleEn,proto3" json:"title_en,omitempty"`
	Author               string               `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Rating               string               `protobuf:"bytes,5,opt,name=rating,proto3" json:"rating,omitempty"`
	DateStart            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=date_start,json=dateStart,proto3" json:"date_start,omitempty"`
	DateFinish           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=date_finish,json=dateFinish,proto3" json:"date_finish,omitempty"`
	Img                  string               `protobuf:"bytes,8,opt,name=img,proto3" json:"img,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_3492beed8154f3a5, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Consignment) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Consignment) GetTitleEn() string {
	if m != nil {
		return m.TitleEn
	}
	return ""
}

func (m *Consignment) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Consignment) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

func (m *Consignment) GetDateStart() *timestamp.Timestamp {
	if m != nil {
		return m.DateStart
	}
	return nil
}

func (m *Consignment) GetDateFinish() *timestamp.Timestamp {
	if m != nil {
		return m.DateFinish
	}
	return nil
}

func (m *Consignment) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

// Создадим пустой запрос
type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3492beed8154f3a5, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

// Ответное сообщение
type GetResponse struct {
	Created              bool         `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3492beed8154f3a5, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *GetResponse) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "mangaProto.Consignment")
	proto.RegisterType((*GetRequest)(nil), "mangaProto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "mangaProto.GetResponse")
}

func init() {
	proto.RegisterFile("api/proto/manga.proto", fileDescriptor_3492beed8154f3a5)
}

var fileDescriptor_3492beed8154f3a5 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xad, 0xcd, 0xf7, 0x18, 0x55, 0xed, 0xb6, 0xa5, 0x5b, 0x2e, 0x45, 0x3e, 0x71, 0xb2, 0x25,
	0x7a, 0x42, 0x48, 0x95, 0x5a, 0x94, 0x70, 0x8d, 0x0c, 0xa7, 0x5c, 0xd0, 0x02, 0x83, 0x59, 0x05,
	0xaf, 0x1d, 0xef, 0x90, 0x43, 0x7e, 0x41, 0xae, 0xf9, 0xc7, 0x91, 0x67, 0x83, 0x20, 0x8a, 0x92,
	0x5c, 0xac, 0xf7, 0x76, 0xde, 0x1b, 0x3f, 0x3f, 0x2f, 0xfc, 0x50, 0x85, 0x8e, 0x8b, 0x32, 0xa7,
	0x3c, 0xce, 0x94, 0x49, 0x55, 0xc4, 0x58, 0x00, 0x93, 0xab, 0x0a, 0xf7, 0x7f, 0xa7, 0x79, 0x9e,
	0xee, 0xd1, 0xa9, 0x56, 0x87, 0x6d, 0x4c, 0x3a, 0x43, 0x4b, 0x2a, 0x2b, 0x9c, 0x38, 0x7c, 0xf0,
	0x21, 0x98, 0xe6, 0xc6, 0xea, 0xd4, 0x64, 0x68, 0x48, 0x7c, 0x06, 0x5f, 0x6f, 0xa4, 0x37, 0xf0,
	0x86, 0xf5, 0xc4, 0xd7, 0x1b, 0xf1, 0x1d, 0x1a, 0xa4, 0x69, 0x8f, 0xd2, 0x1f, 0x78, 0xc3, 0x4e,
	0xe2, 0x88, 0xf8, 0x05, 0x6d, 0x06, 0x4b, 0x34, 0xb2, 0xc6, 0x83, 0x16, 0xf3, 0x0b, 0x23, 0x7a,
	0xd0, 0x54, 0x07, 0xda, 0xe5, 0xa5, 0xac, 0xf3, 0xe0, 0x99, 0x55, 0xe7, 0xa5, 0x22, 0x6d, 0x52,
	0xd9, 0x70, 0xe7, 0x8e, 0x89, 0x31, 0xc0, 0x46, 0x11, 0x2e, 0x2d, 0xa9, 0x92, 0x64, 0x73, 0xe0,
	0x0d, 0x83, 0x51, 0x3f, 0x72, 0xb1, 0xa3, 0x63, 0xec, 0x68, 0x71, 0x8c, 0x9d, 0x74, 0x2a, 0xf5,
	0xbc, 0x12, 0x8b, 0x09, 0x04, 0x6c, 0xdd, 0x6a, 0xa3, 0xed, 0x4e, 0xb6, 0x3e, 0xf4, 0xf2, 0x9b,
	0x2e, 0x59, 0x2d, 0xbe, 0x40, 0x4d, 0x67, 0xa9, 0x6c, 0x73, 0x98, 0x0a, 0x86, 0x5d, 0x80, 0x19,
	0x52, 0x82, 0xb7, 0x07, 0xb4, 0x14, 0xae, 0x20, 0x60, 0x66, 0x8b, 0xdc, 0x58, 0x14, 0x12, 0x5a,
	0xeb, 0x12, 0x15, 0xa1, 0x2b, 0xa7, 0x9d, 0x1c, 0xa9, 0x18, 0x43, 0xb0, 0x3e, 0x15, 0xc8, 0x3d,
	0x05, 0xa3, 0x9f, 0xd1, 0xe9, 0x27, 0x44, 0x67, 0xfd, 0x26, 0xe7, 0xda, 0xd1, 0xa3, 0x07, 0xdd,
	0x52, 0xe9, 0x7b, 0x9c, 0x63, 0x79, 0xa7, 0xd7, 0x28, 0xfe, 0x41, 0x30, 0xe5, 0xb5, 0x0b, 0xae,
	0xf9, 0xad, 0x2d, 0xfd, 0x17, 0x83, 0xb3, 0x98, 0xe1, 0x27, 0xf1, 0x17, 0x3a, 0x33, 0x24, 0xf6,
	0x5b, 0xd1, 0x7b, 0xa5, 0xe3, 0x8f, 0x7b, 0xc7, 0xff, 0xff, 0xdb, 0xf5, 0xd7, 0x28, 0x2e, 0x6e,
	0x52, 0x77, 0xa5, 0x26, 0xfc, 0x5c, 0x35, 0xb9, 0xcc, 0x3f, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xdc, 0xde, 0x5c, 0x5e, 0x72, 0x02, 0x00, 0x00,
}
