import Router from 'next/link';
import type { Metadata } from 'next'
import Link from 'next/link';
// import Image from 'next/image';

import './globals.css'
// import logoMTS from "../img/logo-eco.svg"


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode;}) {
    const manga = "Manga";
    return (
        <html lang='en'>
            <body>
                <header className='border-b  dark:border-slate-100/10'>
                    <nav className='mainContent navigation'  >
                        <Link href="/">
                            <div>Home</div>
                        </Link>
                        <Link href={{pathname: `/rating`}}>
                            <div>{manga}</div>
                        </Link>
                        <Link href={{pathname: `/stuffing`}}>
                            <div>Пользователи</div>
                        </Link>
                        <Link href={{pathname: '/login'}}>
                            <div className='login'>Login</div>
                        </Link>
                    </nav>    
                </header>
                
                <main className='mainContent'>
                    {children}
                </main>
                
            </body>
        </html>
    );
}