env: "local" #local, dev, prod
storage_path: "./storage/storage.db"
http_server: 
  address: "localhost"
  port: ":4040"
  timeout: 5s 
  idle_timeout: 120s
storage: 
  host: "db"
  port: 5432
  database: "rating"
  # user: "postgres"
  # pass: "postgres"
  user: "critic"
  pass: "1234"